#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Pipeline\commands\PipelineHtmlCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->addCommands([
    new PipelineHtmlCommand()
]);

$application->run();
?>